name: SYN2 Controller Windows Forms

on:
  push:
    branches: [ "main" ]
    paths:
      - Syn2Controller.Windows/**
      - .github/workflows/dotnet-winforms.yml
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore Packages
      run: nuget restore Syn2Controller.Windows\Syn2Controller.Windows.csproj -SolutionDirectory .\

    - name: Build
      run: msbuild Syn2Controller.Windows\Syn2Controller.Windows.csproj /nologo /p:Configuration=Release /t:Clean
      shell: pwsh

    - name: Build
      run: msbuild Syn2Controller.Windows\Syn2Controller.Windows.csproj /nologo /p:platform="Any CPU" /p:Configuration=Release /t:Build /p:OutputPath=..\artifacts
      shell: pwsh

    - name: Zip Files
      uses: vimtor/action-zip@v1
      with:
        files: artifacts/
        dest: Syn2Controller.zip

    - name: GH Release
      uses: softprops/action-gh-release@v0.1.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        body: Release
        name: Syn2Controller (${{ env.GITHUB_RUN_ID }})
        draft: true
        files: Syn2Controller-${{ env.GITHUB_RUN_ID }}.zip
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        name: windows
        path: .\artifacts\
